import React from 'react'
import { render, screen } from '@testing-library/react'
import { Button } from './button' // Adjust path as necessary

describe('Button Component', () => {
  it('renders with children', () => {
    render(<Button>Click Me</Button>)
    expect(screen.getByRole('button', { name: /Click Me/i })).toBeInTheDocument()
  })

  it('applies variant classes', () => {
    const { container } = render(<Button variant="destructive">Delete</Button>)
    // This is a basic check, actual class names might be generated by cva
    // and could be more complex to assert precisely without inspecting implementation details.
    // For shadcn/ui, specific class names might be part of the variant.
    expect(container.firstChild).toHaveClass('bg-destructive')
  })

  it('is disabled when disabled prop is true', () => {
    render(<Button disabled>Disabled Button</Button>)
    expect(screen.getByRole('button', { name: /Disabled Button/i })).toBeDisabled()
  })
})
